### ISSUE TITLE
parse failed: template: event/list.json:2: undefined variable "$index"

### ISSUE THREAD

**Issue by anoduck** [ardianta/hugo-fullcalendar#1]
Since I do not desire to have the calendar as my index page, I moved it to 'calendar.html'. When I went to generate the site, I received the following error:

```shell
i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
Error: add site dependencies: load resources: loading templates: "/Site/layouts/event/list.json:2:1": parse failed: template: event/list.json:2: undefined variable "$index"
```
  
This is odd, because I executed hugo inside this repository, and it built the site successfully. Because other parts of my site use jquery, it might be that a newer version of jquery is being loaded instead of the version included in this repository, and that newer version is causing the issue.

**Comment by ardianta** [comment]
Maybe the `.Data.Pages` result is nil.

Have you try to replace it to:

- `.Pages`
- `.Site.Pages`
- `$.Site.Pages`

:file_folder: layouts/event/list.json
```
[
    {{ range $index, $e := (where .Data.Pages "Type" "event" ) }}
    {{ if $index }}, {{ end }}
    {
        "title": "{{ .Title }}",
        "start": "{{ dateFormat "2006-01-02" .Date }}",
        "allDay": {{ .Params.allday }},
        "url": "{{ .Permalink | absURL }}"
    }
    {{ end }}
]
```

**Comment by anoduck** [comment]
...and EUREKA!!!

A) My editor was linting the JSON file on every save and removing the comma after `$index`. This is what created the error. 

B) It finally hit me that the actual data for the calendar is kept within the index.json file, and that the 'event' markdown files are superfluous. I previously thought Hugo was configured to generate `index.json` from  'event' files, so I was confused as to why the calendar was not rendering any events. 

I have been looking for a way to do this within Hugo for quite some time with several projects. I sincerely appreciate the investment you put into creating this.
